### ISSUE TITLE
Settings icon in gene description

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio.vue#44]
Selecting the settings just enables choosing the gene source (refseq or gencode). Is it worth having the settings icon, or just leaving the source dropdown in view at all times?

**Comment by tonydisera** [comment]
I see your point.  I was trying to minimize the visual clutter in this panel, but perhaps this is overkill.

**Comment by tonydisera** [comment]
Fixed.
![Screen Shot 2018-04-13 at 2.01.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5759f0b40b37b00e00e7d3d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f06b7191a37af1122a4f5a5b5ecc3c4a4356bcbbd671f3e57862804e0ebc836e0b26926c47aebc821ee901ba228e4cd7e2b9de1ad2f42f67b6d5db1063474f4dcbed5727a19141c95df448e7495ca315376ae1722431.png)
