### ISSUE TITLE
Side panel title

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio.vue#53]
If the variants panel is open or closed, would it be better if this top bar is the same, e.g. the gene.iobio title is always aligned to the left etc. The open and save functionality could be available in the Files option at the far right, and maybe within the panel for the specific variant I/O?

**Comment by tonydisera** [comment]
Hi Al.  I agree that it would look better to have the title bar go across the full length of the window.  I had to take this out due to a bug with Material design library (Vuetify) because the nav bar over the side panel was obscuring the gene search type-ahead.

Is there some styling changes I could make?

**Comment by AlistairNWard** [comment]
Oh, I see.If there is a bug, I guess we can't change it!! I was looking at the material design page on navigation drawers, and it does show an option for the drawer clipped under the app bar, but if that's not doable, what you have certainly works.

**Comment by tonydisera** [comment]
That's it.  I can't work with you.  The second guessing, the skepticism, the overreaching -- it is just too much.

**Comment by AlistairNWard** [comment]
I want everyone to be operating under a general feeling  of uncomfortableness and being under appreciated. I think I'm doing a great job!

**Comment by tonydisera** [comment]
I'm going home now.  I can't work with this kind of pressure.

**Comment by AlistairNWard** [comment]
I winning so hard now it's amazing...
