### ISSUE TITLE
Deleting genes from gene list does not remove them

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio.vue#60]
1. Open gene.iobio with demo data and let everything load,

2. Open the modal to add a list of genes, and paste a list of genes, removing the 5 demo genes

The 5 demo genes remain, and the added genes are now available. Open the gene list again and remove the demo genes, and they are still not removed; they have to manually removed.

**Comment by tonydisera** [comment]
Thanks.  I will fix this ASAP and the other 'reload' page bug.
