### ISSUE TITLE
Orange box around Gene input remains after inputting a Phenolyzer term

### ISSUE THREAD

**Issue by mvelinder** [tonydisera/gene.iobio.vue#64]
Load data through Files, get prompted to input a gene name (with orange box around search), put a Phenolyzer term in instead, orange box around gene input remains

![image](https://user-images.githubusercontent.com/22081541/39587200-2fcb2d52-4eb6-11e8-9db4-4bd8786fc0c6.png)

**Comment by tonydisera** [comment]
Boom.  You are good.
